In [1]:
import os
import pandas as pd

In [8]:
df = pd.read_pickle('./assets/clean-data/activity_master.pickle')
kmeans_df = pd.read_pickle('./assets/clean-data/kmeans-df.pickle')

kmeans_dict = {}
for ids, locationID in zip(kmeans_df["ClusterGlobalIDs"].values, kmeans_df["LocationID"]):
    if ids:
        for clus in ids[0]:
            kmeans_dict[clus] = locationID

In [9]:
df["LocationID"] = df["cluster_id"].apply(lambda x: kmeans_dict[x])

In [10]:
print(df)

        cluster_id  day_of_week  t_bucket  activity  activity_bucket  \
0                0            0         8         1                0
1                0            0        14         1                0
2                0            0        22         1                0
3                0            0        28         2                0
4                0            0        29         2                0
5                0            0        33         2                0
6                0            0        34         1                0
7                0            1        15         1                0
8                0            1        19         1                0
9                0            1        27         1                0
10               0            1        28         1                0
11               0            1        29         3                1
12               0            1        30         1                0
13               0            1        37         1                0
14               0            2        15         1                0
15               0            2        19         1                0
16               0            2        21         1                0
17               0            2        24         1                0
18               0            2        25         1                0
19               0            2        28         1                0
20               0            2        30         1                0
21               0            2        32         2                0
22               0            2        39         1                0
23               0            2        40         1                0
24               0            3         4         1                0
25               0            3        10         1                0
26               0            3        18         2                0
27               0            3        26         1                0
28               0            3        27         1                0
29               0            3        30         1                0
...            ...          ...       ...       ...              ...
300153        2319            6        18        34                6
300154        2319            6        19        32                6
300155        2319            6        20        58                8
300156        2319            6        21        43                7
300157        2319            6        22        55                8
300158        2319            6        23        41                7
300159        2319            6        24        43                7
300160        2319            6        25        44                7
300161        2319            6        26        52                8
300162        2319            6        27        51                8
300163        2319            6        28        44                7
300164        2319            6        29        44                7
300165        2319            6        30        52                8
300166        2319            6        31        49                8
300167        2319            6        32        28                6
300168        2319            6        33        38                7
300169        2319            6        34        45                7
300170        2319            6        35        45                7
300171        2319            6        36        41                7
300172        2319            6        37        47                8
300173        2319            6        38        50                8
300174        2319            6        39        39                7
300175        2319            6        40        30                6
300176        2319            6        41        27                6
300177        2319            6        42        40                7
300178        2319            6        43        22                5
300179        2319            6        44        24                5
300180        2319            6        45        20                5
300181        2319            6        46        24                5
300182        2319            6        47        27                6

        LocationID
0                1
1                1
2                1
3                1
4                1
5                1
6                1
7                1
8                1
9                1
10               1
11               1
12               1
13               1
14               1
15               1
16               1
17               1
18               1
19               1
20               1
21               1
22               1
23               1
24               1
25               1
26               1
27               1
28               1
29               1
...            ...
300153         263
300154         263
300155         263
300156         263
300157         263
300158         263
300159         263
300160         263
300161         263
300162         263
300163         263
300164         263
300165         263
300166         263
300167         263
300168         263
300169         263
300170         263
300171         263
300172         263
300173         263
300174         263
300175         263
300176         263
300177         263
300178         263
300179         263
300180         263
300181         263
300182         263

[300183 rows x 6 columns]

In [11]:
df.to_pickle('./assets/clean-data/activity_master_wLID.pickle')